title: Jenner个人博客
author: Jenner.Luo
email: jannanlo@163.com
description: > # this means to ignore newlines until "twitter_username:"
  个人技术博客

page:
  list_title: 文章

show_excerpts: false # set to true to show excerpts on the homepage

header_pages:
  - nav/about.md
  - nav/portfolio.md
  
  
theme: minima
  
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
